### PR TITLE
Install older gptq version

### PR DESCRIPTION
**Pull request by paolorechia**
Attempts to add support for older GPTQ-For-LLama version. Unfortunately, not yet working as expected.

1. Cloned `https://github.com/oobabooga/text-generation-webui` into a copy repository: `https://github.com/paolorechia/gptq-for-llama-old`.
2. Added new requirements file `run_server_old_gptq.sh` to install the older version instead.

Make sure to run `pip uninstall gptq_for_llama`  when switching between the different library versions.

Server should run like this:

```bash
export USE_4BIT=true
export USE_13B_MODEL=true
export MODEL_PATH=vicuna-13B-1.1-GPTQ-4bit-128g
export MODEL_CHECKPOINT=vicuna-13B-1.1-GPTQ-4bit-128g.no-act-order.pt
uvicorn servers.vicuna_server:app 
```

### CODE REVIEW

**Comment by paolorechia** [comment]
@alexandme, @unoriginalscreenname 

I've tried addressing your issues by supporting a different GPTQ-For-LLama, forked from this repo: https://github.com/oobabooga/text-generation-webui

However, I could not get it to run properly, this code version does not seem compatible with https://huggingface.co/TheBloke/vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g

Do you guys have any idea which version of the library works for you? Commit, branch etc?

**Comment by alexandme** [comment]
> @alexandme, @unoriginalscreenname
> 
> I've tried addressing your issues by supporting a different GPTQ-For-LLama, forked from this repo: https://github.com/oobabooga/text-generation-webui
> 
> However, I could not get it to run properly, this code version does not seem compatible with https://huggingface.co/TheBloke/vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g
> 
> Do you guys have any idea which version of the library works for you? Commit, branch etc?

Hello, thank you for your time looking into this. Seems like with your version it does not work.
Just to make sure, the version of gptq-for-llama seen after running the installation from this PR is the following:

```
pip show gptq-for-llama
Name: gptq-for-llama
Version: 0.1.0
Summary: 
Home-page: https://github.com/paolorechia/GPTQ-for-LLaMa
```

Not directly related to this, just to mention:
Following config does not work using both old and new version of gptq-for-llama
```
NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6
Quadro P5000
```

This config  does work with new version of gptq-for-llama
```
NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6 
NVIDIA RTX A5000
```

**Comment by paolorechia** [comment]
Hi, @alexandme

thanks for trying it out but it’s not ready yet.

I couldn’t make it to work with oobagooba current version, which is why I’m
wondering if you know which branch or commit of GPTQ-For-LLama works with
your setup (not with my code, but using with oobagooba code).


If you install this PR’s version correctly you should see

Version: 0.1.1


You need to use a different requirements file directly with pip install to
change it. But like I mentioned it’s also not gonna work yet, as it’s not
ready.


Alexander ***@***.***> schrieb am So. 30. Apr. 2023 um 13:37:

**Comment by paolorechia** [comment]
I'm closing this, as I'm gonna try a different approach.

**Pull request closed without merging**
